#
# /etc/nginx-manager/nginx-manager.conf
#

# Configuration file for NGINX Instance Manager

# bind address for all service ports (default "127.0.0.1")
bind_address: 0.0.0.0
# gRPC service port for agent communication (default "10000")
grpc_port: 10000
# gRPC-gateway service port for API and UI (default "11000")
gateway_port: 11000

# SSL server name for use with cert and key below (optional)
#server_name: nginx-manager.example.com
# path to x.509 certificate file (optional)
#cert: /etc/ssl/nginx-manager/nginx-manager.crt
# path to x.509 certificate key file (optional)
#key: /etc/ssl/nginx-manager/nginx-manager.key

# set log level (panic, fatal, error, info, debug, trace; default: info) (default "info")
log:
    level: info
    path: /var/log/nginx-manager/
# Metrics default storage path (default "/tmp/metrics") (directory must be already present)
metrics:
    storage_path: /var/nginx-manager/

# Path to license file
license: /etc/nginx-manager/nginx-manager.lic

scanner:
    # host discovery method (default: ICMP) (ICMP, NONE)
    host_discovery: ICMP
    # ICMP timeout for icmp host sweep (default: 500ms)
    icmp_timeout: 500ms
    # TCP timeout for port connection (default: 500ms)
    tcp_timeout: 500ms

# Forward metrics to F5 Beacon
# beacon:
    # F5 beacon metrics ingestion address
    # address: https://ingestion.ovr.prd.f5aas.com:50443/beacon/v1/ingest-metrics
    # set the access token to authenticate and begin ingesting data into F5 Beacon
    # token: my-beacon-access-token
    # set the max number of points sent to beacon in single request (default: 5000)
    # batch_size: 5000
    # set the interval in milliseconds to send metrics to F5 Beacon if it has not been already written (by reaching batch size)
    # flush_interval: 1000ms

# Forward metrics to influxDB v2
# influxdb:
    # set the InfluxDB address
    # address: http://127.0.0.1:8086/
    # set the access token to authenticate and begin forwarding data to influxdb
    # token: my-influxdb-token
    # org: my-org
    # bucket: my-bucket
    # set the max number of points sent to influxDB in single request (default: 5000)
    # batch_size: 5000
    # set the interval in milliseconds to send metrics to influxdb if it has not been already written (by reaching batch size) (default: 1000ms)
    # flush_interval: 1000ms
    # gzip: false
    # tls:
        # enable tls connecting to influxdb
        # enable: false
        # path to certificate
        # cert: /etc/ssl/influxdb.crt
        # path to certificate key
        # key: /etc/ssl/influxdb.key
        # path to CA cert
        # ca: /etc/ssl/influxdb.pem

# rbac enables enforcement of roles and users (nginx proxy required, ensure you have an admin account working before enabling)
# rbac: true

# Audit Log will log ALL api calls with username header (default: not defined)
# audit_log: /var/log/nginx-manager/audit.log

# if configured the installer is exposed at `/api/v0/scan/manage/<ipaddr>`
# a simple sample is provided to illustrate how that installer is expected to behave.
#installer:
#    filename: sample/scripts/invoke_installer.sh
#    username: joebob
#    port: 9991
#    dir: /opt/nginx/agents
